// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using USLabs.TaskManager.Data.Context;

#nullable disable

namespace USLabs.TaskManager.Data.Migrations
{
    [DbContext(typeof(TaskManagerContext))]
    [Migration("20250602074930_DataSeedersInitial")]
    partial class DataSeedersInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("USLabs.TaskManager.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#007bff");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Categories_UserId_Name");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("54389d4b-0b69-4ca5-8bfd-53846092d09d"),
                            Color = "#392455",
                            CreatedAt = new DateTime(2025, 6, 2, 7, 49, 29, 701, DateTimeKind.Utc).AddTicks(4310),
                            Description = "Et esse voluptates totam harum quae.",
                            Name = "Electronics",
                            UserId = new Guid("5b68c1ab-31bf-4b07-bb2a-2a5110c9177f")
                        },
                        new
                        {
                            Id = new Guid("4bc64640-672b-4358-a27e-0ff93cae0def"),
                            Color = "#465433",
                            CreatedAt = new DateTime(2025, 6, 2, 7, 49, 29, 702, DateTimeKind.Utc).AddTicks(8910),
                            Description = "Quod alias omnis odit ad qui cupiditate.",
                            Name = "Tools",
                            UserId = new Guid("c3d0dd9f-a983-4ed6-a976-6a7c79affe82")
                        },
                        new
                        {
                            Id = new Guid("cc6a631e-8164-4d9a-8ebb-4e3a8ad7d9f9"),
                            Color = "#56276e",
                            CreatedAt = new DateTime(2025, 6, 2, 7, 49, 29, 704, DateTimeKind.Utc).AddTicks(3920),
                            Description = "Voluptas nesciunt sint velit ducimus temporibus non ut.",
                            Name = "Toys",
                            UserId = new Guid("55b988ee-9a25-493c-9efe-6ae7a532edd5")
                        },
                        new
                        {
                            Id = new Guid("dba4043b-7b29-4e5e-a9cb-7219d7987d73"),
                            Color = "#293d26",
                            CreatedAt = new DateTime(2025, 6, 2, 7, 49, 29, 705, DateTimeKind.Utc).AddTicks(9210),
                            Description = "Nemo fuga et error deleniti.",
                            Name = "Sports",
                            UserId = new Guid("25729196-b379-48e7-8783-448743f3a901")
                        });
                });

            modelBuilder.Entity("USLabs.TaskManager.Data.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_TaskItems_DueDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TaskItems_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_TaskItems_UserId");

                    b.ToTable("task_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fbb20d46-e01e-41f9-bd49-9e739e982a95"),
                            CategoryId = new Guid("54389d4b-0b69-4ca5-8bfd-53846092d09d"),
                            CreatedAt = new DateTime(2025, 6, 2, 7, 49, 29, 709, DateTimeKind.Utc).AddTicks(550),
                            Description = "Aliquam amet maiores omnis quod iste. Nobis aut excepturi esse quod rerum. Vel sed molestiae qui sint et alias minus. Impedit quis sapiente quis molestiae aut et consequatur. Culpa aut nostrum ipsa. Dolor eos eum eius.",
                            DueDate = new DateTime(2026, 4, 7, 6, 42, 59, 277, DateTimeKind.Local).AddTicks(4485),
                            Priority = 2,
                            Status = 1,
                            Title = "Ducimus et qui.",
                            UserId = new Guid("5b68c1ab-31bf-4b07-bb2a-2a5110c9177f")
                        },
                        new
                        {
                            Id = new Guid("abbc5942-f4c7-4944-8481-df1a5eef661e"),
                            CategoryId = new Guid("54389d4b-0b69-4ca5-8bfd-53846092d09d"),
                            CreatedAt = new DateTime(2025, 6, 2, 7, 49, 29, 710, DateTimeKind.Utc).AddTicks(7480),
                            Description = "Sit doloribus consectetur at nesciunt omnis occaecati non. Id illo quas optio possimus exercitationem voluptas excepturi occaecati. Voluptatem omnis velit. Sint ut quo sint accusantium nobis ex debitis soluta. Est totam sed illum libero sint. Vero quos magnam quam et dolorem.",
                            DueDate = new DateTime(2026, 3, 31, 19, 43, 39, 675, DateTimeKind.Local).AddTicks(9352),
                            Priority = 3,
                            Status = 2,
                            Title = "Excepturi atque doloribus.",
                            UserId = new Guid("5b68c1ab-31bf-4b07-bb2a-2a5110c9177f")
                        },
                        new
                        {
                            Id = new Guid("fc185c9f-ab03-4099-a545-0ff807f9ca46"),
                            CategoryId = new Guid("4bc64640-672b-4358-a27e-0ff93cae0def"),
                            CreatedAt = new DateTime(2025, 6, 2, 7, 49, 29, 712, DateTimeKind.Utc).AddTicks(3440),
                            Description = "In ea excepturi. Eos perferendis et. Est ipsum deserunt non sunt reiciendis eligendi omnis. Ipsa ex consequatur. Atque consequatur voluptatem nesciunt in quia minus labore sit.",
                            DueDate = new DateTime(2025, 12, 10, 9, 55, 10, 943, DateTimeKind.Local).AddTicks(9826),
                            Priority = 3,
                            Status = 4,
                            Title = "Nemo dolorem voluptatum.",
                            UserId = new Guid("c3d0dd9f-a983-4ed6-a976-6a7c79affe82")
                        },
                        new
                        {
                            Id = new Guid("3934341d-d572-4306-8a84-d5bb8270a4dd"),
                            CategoryId = new Guid("4bc64640-672b-4358-a27e-0ff93cae0def"),
                            CreatedAt = new DateTime(2025, 6, 2, 7, 49, 29, 714, DateTimeKind.Utc).AddTicks(820),
                            Description = "Laborum inventore porro provident excepturi dicta qui accusantium et pariatur. Commodi qui reiciendis sit quam cum nobis maxime illum. Vel voluptatum totam doloremque laudantium consequatur sapiente suscipit sed eos. Impedit accusantium rerum ut eveniet sunt id. Natus accusantium ea temporibus occaecati dolorem.",
                            DueDate = new DateTime(2026, 2, 21, 11, 56, 18, 170, DateTimeKind.Local).AddTicks(2132),
                            Priority = 1,
                            Status = 3,
                            Title = "Ratione fugit ut.",
                            UserId = new Guid("c3d0dd9f-a983-4ed6-a976-6a7c79affe82")
                        },
                        new
                        {
                            Id = new Guid("a8dd6978-4e78-4a21-aedf-db2bff27a6e5"),
                            CategoryId = new Guid("cc6a631e-8164-4d9a-8ebb-4e3a8ad7d9f9"),
                            CreatedAt = new DateTime(2025, 6, 2, 7, 49, 29, 715, DateTimeKind.Utc).AddTicks(7770),
                            Description = "Cumque vel laboriosam quia nam sit aspernatur. Quidem rerum qui inventore quia autem iste voluptatem. Consequatur velit blanditiis facilis.",
                            DueDate = new DateTime(2025, 9, 19, 14, 10, 38, 626, DateTimeKind.Local).AddTicks(659),
                            Priority = 1,
                            Status = 4,
                            Title = "Perferendis est natus.",
                            UserId = new Guid("55b988ee-9a25-493c-9efe-6ae7a532edd5")
                        },
                        new
                        {
                            Id = new Guid("0e15410f-ed52-49ef-8c0e-c2816b2fb732"),
                            CategoryId = new Guid("cc6a631e-8164-4d9a-8ebb-4e3a8ad7d9f9"),
                            CreatedAt = new DateTime(2025, 6, 2, 7, 49, 29, 717, DateTimeKind.Utc).AddTicks(4760),
                            Description = "Aperiam id non aliquam voluptas aut. Non et nulla facere vel. Facere molestiae odio voluptatem ipsa iste vero molestiae recusandae vero. Eos ut neque quae odit occaecati. Exercitationem beatae magnam suscipit et non ab ratione quibusdam excepturi. Est est accusamus autem cumque quod.",
                            DueDate = new DateTime(2025, 8, 19, 11, 41, 4, 917, DateTimeKind.Local).AddTicks(3530),
                            Priority = 2,
                            Status = 1,
                            Title = "Aut asperiores nihil.",
                            UserId = new Guid("55b988ee-9a25-493c-9efe-6ae7a532edd5")
                        },
                        new
                        {
                            Id = new Guid("65fb15fe-3ee2-4d7d-8563-82344af2221c"),
                            CategoryId = new Guid("dba4043b-7b29-4e5e-a9cb-7219d7987d73"),
                            CreatedAt = new DateTime(2025, 6, 2, 7, 49, 29, 719, DateTimeKind.Utc).AddTicks(640),
                            Description = "Consectetur laboriosam porro. Itaque debitis qui quia non autem. Sed nesciunt laboriosam. Sunt voluptatem maxime eum consequatur vero iste ipsam ea. Ut doloremque aliquid iure id praesentium natus. Architecto sapiente sit deserunt.",
                            DueDate = new DateTime(2025, 7, 1, 0, 28, 55, 584, DateTimeKind.Local).AddTicks(3562),
                            Priority = 1,
                            Status = 4,
                            Title = "Eaque ut praesentium.",
                            UserId = new Guid("25729196-b379-48e7-8783-448743f3a901")
                        },
                        new
                        {
                            Id = new Guid("b965b0a7-6f90-4bef-8066-8c86a8bf3636"),
                            CategoryId = new Guid("dba4043b-7b29-4e5e-a9cb-7219d7987d73"),
                            CreatedAt = new DateTime(2025, 6, 2, 7, 49, 29, 720, DateTimeKind.Utc).AddTicks(7160),
                            Description = "Possimus voluptas ea quis nulla excepturi cumque doloribus. Ex iure sit voluptas dolor optio recusandae debitis est. Qui alias dolores officiis harum velit iure eum. Mollitia aspernatur voluptatem harum aut dignissimos omnis illum qui. Omnis asperiores at architecto dolorum ut dolorem debitis vero. Vel voluptatem nisi harum dolores consequuntur.",
                            DueDate = new DateTime(2026, 5, 1, 20, 29, 13, 920, DateTimeKind.Local).AddTicks(1258),
                            Priority = 2,
                            Status = 3,
                            Title = "Et corporis et.",
                            UserId = new Guid("25729196-b379-48e7-8783-448743f3a901")
                        });
                });

            modelBuilder.Entity("USLabs.TaskManager.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b68c1ab-31bf-4b07-bb2a-2a5110c9177f"),
                            CreatedAt = new DateTime(2025, 6, 2, 7, 49, 29, 698, DateTimeKind.Utc).AddTicks(780),
                            Email = "Alf_Jenkins@yahoo.com",
                            FirstName = "Lauren",
                            IsActive = true,
                            LastName = "Pouros",
                            PasswordHash = "m5iJOS1KfJ"
                        },
                        new
                        {
                            Id = new Guid("c3d0dd9f-a983-4ed6-a976-6a7c79affe82"),
                            CreatedAt = new DateTime(2025, 6, 2, 7, 49, 29, 698, DateTimeKind.Utc).AddTicks(2130),
                            Email = "Damian88@yahoo.com",
                            FirstName = "Gussie",
                            IsActive = true,
                            LastName = "MacGyver",
                            PasswordHash = "slFEMNMdG8"
                        },
                        new
                        {
                            Id = new Guid("55b988ee-9a25-493c-9efe-6ae7a532edd5"),
                            CreatedAt = new DateTime(2025, 6, 2, 7, 49, 29, 698, DateTimeKind.Utc).AddTicks(2270),
                            Email = "Derrick50@hotmail.com",
                            FirstName = "Rodolfo",
                            IsActive = true,
                            LastName = "Schowalter",
                            PasswordHash = "kh2f61zoyh"
                        },
                        new
                        {
                            Id = new Guid("25729196-b379-48e7-8783-448743f3a901"),
                            CreatedAt = new DateTime(2025, 6, 2, 7, 49, 29, 698, DateTimeKind.Utc).AddTicks(2400),
                            Email = "Llewellyn3@hotmail.com",
                            FirstName = "Abraham",
                            IsActive = true,
                            LastName = "Beier",
                            PasswordHash = "pnv3rR9ljO"
                        });
                });

            modelBuilder.Entity("USLabs.TaskManager.Data.Entities.Category", b =>
                {
                    b.HasOne("USLabs.TaskManager.Data.Entities.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("USLabs.TaskManager.Data.Entities.TaskItem", b =>
                {
                    b.HasOne("USLabs.TaskManager.Data.Entities.Category", "Category")
                        .WithMany("TaskItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("USLabs.TaskManager.Data.Entities.User", "User")
                        .WithMany("TaskItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("USLabs.TaskManager.Data.Entities.Category", b =>
                {
                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("USLabs.TaskManager.Data.Entities.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("TaskItems");
                });
#pragma warning restore 612, 618
        }
    }
}
